package com.sise.TiendaTecnologica.ui;

import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alex_PC
 */
//PRUEBA DE PUBLICACION 01 ALEX
public class PrincipalUI extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalUI
     */
    public PrincipalUI() {
        initComponents();
        initConfig();
    }
private void initConfig(){
    this.setTitle("SISTEMA DE VENTAS - TIENDA DE ARTICULOS DE TECNOLOGIA");
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        PnlDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnNuevaVenta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        mnAlmacen = new javax.swing.JMenu();
        mnAgregaProductos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PnlDesktopLayout = new javax.swing.GroupLayout(PnlDesktop);
        PnlDesktop.setLayout(PnlDesktopLayout);
        PnlDesktopLayout.setHorizontalGroup(
            PnlDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        PnlDesktopLayout.setVerticalGroup(
            PnlDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/ventas.png"))); // NOI18N
        jMenu2.setText("Ventas");

        mnNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/nventas.png"))); // NOI18N
        mnNuevaVenta.setText("Nueva Venta");
        mnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNuevaVentaActionPerformed(evt);
            }
        });
        jMenu2.add(mnNuevaVenta);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/compras.png"))); // NOI18N
        jMenu3.setText("Compras");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/ncompras.png"))); // NOI18N
        jMenuItem3.setText("Nueva Compra");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/clientes.png"))); // NOI18N
        jMenu8.setText("Clientes");

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/ncliente.png"))); // NOI18N
        jMenu13.setText("Nuevo Cliente");
        jMenu8.add(jMenu13);

        jMenuBar1.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/proveedores.png"))); // NOI18N
        jMenu9.setText("Proveedores");

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/nproveedor.png"))); // NOI18N
        jMenu12.setText("Nuevo Proveedor");
        jMenu9.add(jMenu12);

        jMenuBar1.add(jMenu9);

        mnAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/almacen.png"))); // NOI18N
        mnAlmacen.setText("Almacen");

        mnAgregaProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/nproducto.png"))); // NOI18N
        mnAgregaProductos.setText("Agregar Producto");
        mnAgregaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAgregaProductosActionPerformed(evt);
            }
        });
        mnAlmacen.add(mnAgregaProductos);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/nservicio.png"))); // NOI18N
        jMenuItem2.setText("Agreagar Servicio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnAlmacen.add(jMenuItem2);

        jMenuBar1.add(mnAlmacen);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/cerrar.png"))); // NOI18N
        jMenu11.setText("Salir");
        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNuevaVentaActionPerformed
      NuevaVentaUI nuevaventaUI = new NuevaVentaUI();
      nuevaventaUI.setVisible(true);
      PnlDesktop.add(nuevaventaUI);
    }//GEN-LAST:event_mnNuevaVentaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnAgregaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAgregaProductosActionPerformed
      AgregaProductosUI agregaProductosUI = new AgregaProductosUI();
      agregaProductosUI.setVisible(true);
      PnlDesktop.add(agregaProductosUI);
    }//GEN-LAST:event_mnAgregaProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane PnlDesktop;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mnAgregaProductos;
    private javax.swing.JMenu mnAlmacen;
    private javax.swing.JMenuItem mnNuevaVenta;
    // End of variables declaration//GEN-END:variables
}
