package com.sise.TiendaTecnologica.ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alex_PC
 */
//PRUEBA DE PUBLICACION 02 ALEX ALEX..
public class PrincipalUI extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalUI
     */
    public PrincipalUI() {
        initComponents();
        initConfig();
    }
private void initConfig(){
    this.setTitle("SISTEMA DE VENTAS - TIENDA DE ARTICULOS DE TECNOLOGIA");
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        PnlDesktop = new javax.swing.JDesktopPane();
        btnsalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnNuevaVenta = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mnnuevocliente = new javax.swing.JMenuItem();
        mnAlmacen = new javax.swing.JMenu();
        mnAgregaProductos = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/cerrar.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        PnlDesktop.setLayer(btnsalir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PnlDesktopLayout = new javax.swing.GroupLayout(PnlDesktop);
        PnlDesktop.setLayout(PnlDesktopLayout);
        PnlDesktopLayout.setHorizontalGroup(
            PnlDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlDesktopLayout.createSequentialGroup()
                .addContainerGap(553, Short.MAX_VALUE)
                .addComponent(btnsalir)
                .addContainerGap())
        );
        PnlDesktopLayout.setVerticalGroup(
            PnlDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlDesktopLayout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addComponent(btnsalir)
                .addContainerGap())
        );

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/ventas.png"))); // NOI18N
        jMenu2.setText("Ventas");

        mnNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/nventas.png"))); // NOI18N
        mnNuevaVenta.setText("Nueva Venta");
        mnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNuevaVentaActionPerformed(evt);
            }
        });
        jMenu2.add(mnNuevaVenta);

        jMenuBar1.add(jMenu2);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/clientes.png"))); // NOI18N
        jMenu8.setText("Clientes");

        mnnuevocliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/ncliente.png"))); // NOI18N
        mnnuevocliente.setText("Nuevo Cliente");
        mnnuevocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnnuevoclienteActionPerformed(evt);
            }
        });
        jMenu8.add(mnnuevocliente);

        jMenuBar1.add(jMenu8);

        mnAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/almacen.png"))); // NOI18N
        mnAlmacen.setText("Almacen");

        mnAgregaProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sise/TiendaTecnologica/assets/nproducto.png"))); // NOI18N
        mnAgregaProductos.setText("Agregar Producto");
        mnAgregaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAgregaProductosActionPerformed(evt);
            }
        });
        mnAlmacen.add(mnAgregaProductos);

        jMenuBar1.add(mnAlmacen);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNuevaVentaActionPerformed
      NuevaVentaUI nuevaventaUI = new NuevaVentaUI();
      nuevaventaUI.setVisible(true);
      PnlDesktop.add(nuevaventaUI);
    }//GEN-LAST:event_mnNuevaVentaActionPerformed

    private void mnAgregaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAgregaProductosActionPerformed
      AgregaProductosUI agregaProductosUI = new AgregaProductosUI();
      agregaProductosUI.setVisible(true);
      PnlDesktop.add(agregaProductosUI);
    }//GEN-LAST:event_mnAgregaProductosActionPerformed

    private void mnnuevoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnnuevoclienteActionPerformed
        // TODO add your handling code here:
      NuevoClienteUI nuevoClienteUI = new NuevoClienteUI();
      nuevoClienteUI.setVisible(true);
      PnlDesktop.add(nuevoClienteUI);
    }//GEN-LAST:event_mnnuevoclienteActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
         int confirm = JOptionPane.showConfirmDialog(this, 
        "¿Desea cerrar esta ventana?", 
        "Confirmar salida", 
        JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        dispose();
    }
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane PnlDesktop;
    private javax.swing.JButton btnsalir;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem mnAgregaProductos;
    private javax.swing.JMenu mnAlmacen;
    private javax.swing.JMenuItem mnNuevaVenta;
    private javax.swing.JMenuItem mnnuevocliente;
    // End of variables declaration//GEN-END:variables
}
